import type { AiProviderPreset } from '@/domain/models'

export const builtinAiProviderPresets: AiProviderPreset[] = [
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    providerKind: 'open_ai_compatible',
    recommendedBaseUrl: 'https://api.deepseek.com',
    models: [
      { id: 'deepseek-chat', displayName: 'DeepSeek Chat', contextWindowTokens: 131072, maxOutputTokens: 8192, supportsVision: false },
      { id: 'deepseek-reasoner', displayName: 'DeepSeek Reasoner', contextWindowTokens: 131072, maxOutputTokens: 65536, supportsVision: false },
    ],
    supportsVision: false,
    documentationUrl: 'https://api-docs.deepseek.com/',
    builtin: true,
    enabled: true,
    defaultPreset: true,
  },
  {
    id: 'zhipu-glm',
    displayName: '智谱 GLM',
    providerKind: 'open_ai_compatible',
    recommendedBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    models: [
      { id: 'glm-5.2', displayName: 'GLM-5.2', contextWindowTokens: 131072, maxOutputTokens: 65536, supportsVision: false },
      { id: 'glm-5v-turbo', displayName: 'GLM-5V-Turbo', contextWindowTokens: 131072, maxOutputTokens: 16384, supportsVision: true },
    ],
    supportsVision: true,
    documentationUrl: 'https://docs.bigmodel.cn/cn/guide/develop/http/introduction',
    builtin: true,
    enabled: true,
    defaultPreset: false,
  },
  {
    id: 'moonshot-kimi',
    displayName: 'Moonshot / Kimi',
    providerKind: 'open_ai_compatible',
    recommendedBaseUrl: 'https://api.moonshot.cn/v1',
    models: [
      { id: 'kimi-k3', displayName: 'Kimi K3', contextWindowTokens: 262144, maxOutputTokens: 65536, supportsVision: true },
      { id: 'kimi-k2.6', displayName: 'Kimi K2.6', contextWindowTokens: 262144, maxOutputTokens: 65536, supportsVision: true },
    ],
    supportsVision: true,
    documentationUrl: 'https://platform.kimi.com/docs/api/chat',
    builtin: true,
    enabled: true,
    defaultPreset: false,
  },
  {
    id: 'openai',
    displayName: 'OpenAI',
    providerKind: 'open_ai_compatible',
    recommendedBaseUrl: 'https://api.openai.com/v1',
    models: [
      { id: 'gpt-5.6', displayName: 'GPT-5.6', contextWindowTokens: 400000, maxOutputTokens: 128000, supportsVision: true },
      { id: 'gpt-5.6-terra', displayName: 'GPT-5.6 Terra', contextWindowTokens: 400000, maxOutputTokens: 128000, supportsVision: true },
      { id: 'gpt-5.6-luna', displayName: 'GPT-5.6 Luna', contextWindowTokens: 400000, maxOutputTokens: 128000, supportsVision: true },
    ],
    supportsVision: true,
    documentationUrl: 'https://developers.openai.com/api/docs/guides/latest-model',
    builtin: true,
    enabled: true,
    defaultPreset: false,
  },
  {
    id: 'custom-openai-compatible',
    displayName: '自定义 OpenAI-compatible',
    providerKind: 'open_ai_compatible',
    recommendedBaseUrl: '',
    models: [],
    supportsVision: false,
    documentationUrl: '',
    builtin: true,
    enabled: true,
    defaultPreset: false,
  },
]
