[package]
name = "muriarc-store-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
muriarc-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres", "migrate", "macros"] }
uuid.workspace = true

[dev-dependencies]
muriarc-core = { path = "../core", features = ["test-support"] }
tokio.workspace = true