<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { useMessage } from 'naive-ui'
import PageHeader from '@/components/PageHeader.vue'
import { gateway,type AiExtractionRecord,type PrivateImageRecord } from '@/services/gateway'
const msg=useMessage(),images=ref<PrivateImageRecord[]>([]),drafts=ref<AiExtractionRecord[]>([]),projects=ref<Array<{id:string;name:string}>>([]),experiments=ref<Array<{id:string;projectId:string;name:string}>>([]),events=ref<Array<{id:string;experimentId:string;label:string}>>([]),project=ref<string>(),experiment=ref<string>(),event=ref<string>(),selectedImage=ref<string>(),busy=ref(false)
const projectOptions=computed(()=>projects.value.map(x=>({label:x.name,value:x.id}))),experimentOptions=computed(()=>experiments.value.filter(x=>x.projectId===project.value).map(x=>({label:x.name,value:x.id}))),eventOptions=computed(()=>events.value.filter(x=>x.experimentId===experiment.value).map(x=>({label:x.label,value:x.id})))
async function load(){if(!gateway.listPrivateImages)return;images.value=await gateway.listPrivateImages();drafts.value=await gateway.listAiExtractions?.(project.value)??[]}
async function upload(ev:Event){const files=Array.from((ev.target as HTMLInputElement).files??[]);if(files.reduce((n,f)=>n+f.size,0)>500*1024*1024){msg.error('单批总量不能超过 500 MiB');return}busy.value=true;for(const file of files){try{await gateway.uploadPrivateImage?.(file)}catch(e){msg.error(file.name+'：'+(e instanceof Error?e.message:'上传失败'))}}busy.value=false;await load()}
async function extract(){if(!selectedImage.value||!project.value||!experiment.value||!event.value||!gateway.createAiExtraction)return;busy.value=true;try{await gateway.createAiExtraction({private_image_id:selectedImage.value,project_id:project.value,experiment_id:experiment.value,experiment_event_id:event.value});msg.success('已生成结构化草稿，请核对置信度和单元格差异');await load()}catch(e){msg.error(e instanceof Error?e.message:'提取失败')}finally{busy.value=false}}
async function approve(d:AiExtractionRecord){if(!gateway.approveAiExtraction)return;busy.value=true;try{await gateway.approveAiExtraction(d.id,d.meta.revision,d.items.map((_,i)=>i));msg.success('已原子写入 Observation、Audit 与 Provenance');await load()}catch(e){msg.error(e instanceof Error?e.message:'批准失败')}finally{busy.value=false}}
onMounted(async()=>{[projects.value,experiments.value]=await Promise.all([gateway.listProjects(),gateway.listExperiments()]);for(const x of experiments.value){events.value.push(...await gateway.listExperimentEvents(x.id))}project.value=projects.value[0]?.id;await load()})
</script>
<template><div class="page"><PageHeader title="私人 AI 图片" description="按用户/会话隔离；未归档图片从最后活动起保留 30 天，运行中与待审批图片不清理。"/>
<section class="controls surface"><label class="pick">上传图片<input type="file" multiple accept="image/*,.tif,.tiff,.heic,.heif" capture="environment" @change="upload"/></label><n-select v-model:value="project" :options="projectOptions" placeholder="项目"/><n-select v-model:value="experiment" :options="experimentOptions" placeholder="实验"/><n-select v-model:value="event" :options="eventOptions" placeholder="采集节点"/><n-button type="primary" :loading="busy" :disabled="!selectedImage||!event" @click="extract">视觉提取</n-button></section>
<section class="images"><article v-for="x in images" :key="x.image.id" class="surface" :class="{selected:selectedImage===x.image.id}" @click="selectedImage=x.image.id"><img :src="x.previewHref"/><strong>{{x.fileName}}</strong><span>{{(x.sizeBytes/1048576).toFixed(1)}} MiB · {{x.retentionDays}} 天后到期</span><n-tag size="small">{{x.image.status}}</n-tag></article><n-empty v-if="!images.length" description="尚未上传私人图片"/></section>
<h2>提取草稿</h2><section class="drafts"><article v-for="d in drafts" :key="d.id" class="surface"><header><strong>{{d.status}}</strong><span>{{d.items.length}} 个候选值</span></header><div v-for="(x,i) in d.items" :key="i" class="diff"><span>{{x.source_label??x.observation.definition_id}}</span><code>{{JSON.stringify(x.value.value)}}</code><n-progress type="line" :percentage="Math.round(x.confidence*100)" :show-indicator="true"/></div><n-button v-if="d.status==='pending_approval'||d.status==='draft'" type="primary" :loading="busy" @click="approve(d)">批准全部选中项并写回</n-button></article></section>
</div></template>
<style scoped>.controls{display:grid;grid-template-columns:auto repeat(3,minmax(130px,1fr)) auto;gap:9px;padding:12px;margin-bottom:12px}.pick{display:flex;align-items:center;padding:0 14px;border-radius:7px;color:#fff;background:var(--muri-primary);cursor:pointer}.pick input{display:none}.images{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:9px}.images article{display:flex;padding:9px;flex-direction:column;gap:5px;cursor:pointer}.images article.selected{outline:2px solid var(--muri-primary)}.images img{width:100%;height:150px;object-fit:cover;border-radius:6px}.images span,.drafts span{color:var(--muri-text-tertiary);font-size:11px}.drafts{display:grid;gap:10px}.drafts article{padding:14px}.drafts header{display:flex;justify-content:space-between}.diff{display:grid;grid-template-columns:1fr 1fr 180px;gap:10px;padding:8px 0;border-bottom:1px solid var(--muri-border)}@media(max-width:800px){.controls{grid-template-columns:1fr}.images{grid-template-columns:1fr 1fr}.diff{grid-template-columns:1fr}.images img{height:130px}}@media(max-width:460px){.images{grid-template-columns:1fr}}</style>
